# Generated by Django 5.1.3 on 2025-02-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("agreed_meters", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fs_number", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField()),
                ("drilled_meters", models.IntegerField()),
                ("morning_start_time", models.TimeField()),
                ("morning_end_time", models.TimeField()),
                ("afternoon_start_time", models.TimeField()),
                ("afternoon_end_time", models.TimeField()),
                (
                    "unit_price_without_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("buyer_name", models.CharField(max_length=255)),
                ("tin_number", models.CharField(max_length=100)),
                (
                    "bank_transferred_from_account_number",
                    models.CharField(max_length=50),
                ),
                ("bank_transferred_from_name", models.CharField(max_length=100)),
                (
                    "bank_transferred_from_account_sender_name",
                    models.CharField(max_length=255),
                ),
                ("bank_transferred_to_account_number", models.CharField(max_length=50)),
                ("bank_transferred_to_name", models.CharField(max_length=100)),
                (
                    "bank_transferred_to_account_receiver_name",
                    models.CharField(max_length=255),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="sales.project",
                    ),
                ),
            ],
        ),
    ]
