# Generated by Django 5.1.3 on 2025-02-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankTransferDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_account_number", models.CharField(max_length=50)),
                ("from_bank_name", models.CharField(max_length=100)),
                ("from_sender_name", models.CharField(max_length=100)),
                ("to_account_number", models.CharField(max_length=50)),
                ("to_bank_name", models.CharField(max_length=100)),
                ("to_receiver_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("meters_agreed", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.contract"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fs_number", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "drilled_meters",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("worked_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "unit_price_without_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_price_including_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("buyer_name", models.CharField(max_length=100)),
                ("tin_number", models.CharField(max_length=50)),
                (
                    "bank_transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.banktransferdetail",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.project"
                    ),
                ),
            ],
        ),
    ]
