# Generated by Django 5.1.3 on 2025-02-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("Pcs", "Pcs"), ("Liter", "Liter"), ("Kg", "Kg")],
                        max_length=50,
                    ),
                ),
                ("seller_name", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_purchase", models.DateField()),
                ("date_of_purchase_ethiopian", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.category",
                    ),
                ),
            ],
        ),
    ]
