# Generated by Django 5.1.3 on 2025-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FS_number", models.CharField(max_length=100)),
                (
                    "Receipt",
                    models.CharField(
                        choices=[("with", "With"), ("without", "Without")],
                        max_length=100,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        choices=[
                            ("Shank", "Shank"),
                            ("Rod", "Rod"),
                            ("Bit", "Bit"),
                            ("Coupling", "Coupling"),
                            ("Liquid consumable", "Liquid consumable"),
                            ("Gas consumable", "Gas consumable"),
                            ("Filter", "Filter"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("custom_item_name", models.CharField(blank=True, max_length=100)),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            ("Main Consumables", "Main Consumables"),
                            ("Lubricants", "Lubricants"),
                            ("Service Items", "Service Items"),
                            ("Maintenance Items", "Maintenance Items"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Paid", "Paid")], max_length=100
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "unit_price_before_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Finished", "Finished"),
                            ("Unfinished", "Unfinished"),
                        ],
                        max_length=100,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("Pcs", "Pcs"), ("Liter", "Liter"), ("Kg", "Kg")],
                        max_length=50,
                    ),
                ),
                ("seller_name", models.CharField(blank=True, max_length=100)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_of_purchase", models.DateField()),
                ("date_of_bank_transfer", models.DateField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("brand", models.CharField(blank=True, max_length=50)),
                (
                    "Transferred_to_bank_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CBE", "Commercial Bank of Ethiopia"),
                            ("Awash Bank", "Awash International Bank"),
                            ("Dashen Bank", "Dashen Bank S.C."),
                            ("Bank of Abyssinia", "Bank of Abyssinia S.C."),
                            ("Wegagen Bank", "Wegagen Bank S.C."),
                            ("Nib International Bank", "Nib International Bank S.C."),
                            ("Hibret Bank", "Hibret Bank S.C."),
                            ("Oromia Bank", "Oromia Bank S.C."),
                            (
                                "Cooperative Bank of Oromia",
                                "Cooperative Bank of Oromia",
                            ),
                            ("Berhan Bank", "Berhan International Bank S.C."),
                            ("Bunna Bank", "Bunna International Bank S.C."),
                            ("Zemen Bank", "Zemen Bank S.C."),
                            ("Enat Bank", "Enat Bank S.C."),
                            ("Global Bank Ethiopia", "Global Bank Ethiopia S.C."),
                            (
                                "Addis International Bank",
                                "Addis International Bank S.C.",
                            ),
                            ("Abay Bank", "Abay Bank S.C."),
                            ("Shabelle Bank", "Shabelle Bank S.C."),
                            ("ZamZam Bank", "ZamZam Bank S.C."),
                            ("Goh Betoch Bank", "Goh Betoch Bank S.C."),
                            ("Ahadu Bank", "Ahadu Bank S.C."),
                            ("Hijra Bank", "Hijra Bank S.C."),
                            ("Tsehay Bank", "Tsehay Bank S.C."),
                            ("Siinqee Bank", "Siinqee Bank S.C."),
                            ("Tsedey Bank", "Tsedey Bank S.C."),
                            ("Gadaa Bank", "Gadaa Bank S.C."),
                            ("Amhara Bank", "Amhara Bank S.C."),
                            ("Rammis Bank", "Rammis Bank S.C."),
                            ("Siket Bank", "Siket Bank S.C."),
                            ("Sidama Bank", "Sidama Bank S.C."),
                            ("Omo Bank", "Omo Bank S.C."),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "Transferred_from_bank_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CBE", "Commercial Bank of Ethiopia"),
                            ("Awash Bank", "Awash International Bank"),
                            ("Dashen Bank", "Dashen Bank S.C."),
                            ("Bank of Abyssinia", "Bank of Abyssinia S.C."),
                            ("Wegagen Bank", "Wegagen Bank S.C."),
                            ("Nib International Bank", "Nib International Bank S.C."),
                            ("Hibret Bank", "Hibret Bank S.C."),
                            ("Oromia Bank", "Oromia Bank S.C."),
                            (
                                "Cooperative Bank of Oromia",
                                "Cooperative Bank of Oromia",
                            ),
                            ("Berhan Bank", "Berhan International Bank S.C."),
                            ("Bunna Bank", "Bunna International Bank S.C."),
                            ("Zemen Bank", "Zemen Bank S.C."),
                            ("Enat Bank", "Enat Bank S.C."),
                            ("Global Bank Ethiopia", "Global Bank Ethiopia S.C."),
                            (
                                "Addis International Bank",
                                "Addis International Bank S.C.",
                            ),
                            ("Abay Bank", "Abay Bank S.C."),
                            ("Shabelle Bank", "Shabelle Bank S.C."),
                            ("ZamZam Bank", "ZamZam Bank S.C."),
                            ("Goh Betoch Bank", "Goh Betoch Bank S.C."),
                            ("Ahadu Bank", "Ahadu Bank S.C."),
                            ("Hijra Bank", "Hijra Bank S.C."),
                            ("Tsehay Bank", "Tsehay Bank S.C."),
                            ("Siinqee Bank", "Siinqee Bank S.C."),
                            ("Tsedey Bank", "Tsedey Bank S.C."),
                            ("Gadaa Bank", "Gadaa Bank S.C."),
                            ("Amhara Bank", "Amhara Bank S.C."),
                            ("Rammis Bank", "Rammis Bank S.C."),
                            ("Siket Bank", "Siket Bank S.C."),
                            ("Sidama Bank", "Sidama Bank S.C."),
                            ("Omo Bank", "Omo Bank S.C."),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "Transferred_to_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Transferred_from_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Transferred_to_receiver_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Transferred_from_sender_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-date_of_purchase"],
            },
        ),
    ]
