# Generated by Django 5.1.3 on 2025-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FS_number", models.CharField(max_length=100)),
                (
                    "Receipt",
                    models.CharField(
                        choices=[("with", "With"), ("without", "Without")],
                        max_length=100,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        choices=[
                            ("Shank", "Shank"),
                            ("Rod", "Rod"),
                            ("Bit", "Bit"),
                            ("Coupling", "Coupling"),
                            ("Liquid consumable", "Liquid consumable"),
                            ("Gas consumable", "Gas consumable"),
                            ("Filter", "Filter"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "custom_item_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            ("Main Consumables", "Main Consumables"),
                            ("Lubricants", "Lubricants"),
                            ("Service Items", "Service Items"),
                            ("Maintenance Items", "Maintenance Items"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "credit_paid",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Paid", "Paid")], max_length=100
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("CBE", "Commercial Bank of Ethiopia"),
                            ("Abyssinia Bank", "Abyssinia Bank"),
                            ("Oromia Bank", "Oromia Bank"),
                        ],
                        max_length=200,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "unit_price_before_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Finished", "Finished"),
                            ("Unfinished", "Unfinished"),
                        ],
                        max_length=100,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("Pcs", "Pcs"), ("Liter", "Liter"), ("Kg", "Kg")],
                        max_length=50,
                    ),
                ),
                ("seller_name", models.CharField(blank=True, max_length=100)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_of_purchase", models.DateField()),
                (
                    "date_of_purchase_ethiopian",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("brand", models.CharField(blank=True, max_length=50)),
                (
                    "Transferred_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CBE", "Commercial Bank of Ethiopia"),
                            ("Abyssinia Bank", "Abyssinia Bank"),
                            ("Oromia Bank", "Oromia Bank"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "Transferred_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CBE", "Commercial Bank of Ethiopia"),
                            ("Abyssinia Bank", "Abyssinia Bank"),
                            ("Oromia Bank", "Oromia Bank"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_of_purchase"],
            },
        ),
    ]
