# Generated by Django 5.1.3 on 2025-02-28 17:29

import purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="bank_transfer_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=purchase.models.upload_to_bank_transfers,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="receipt_file",
            field=models.FileField(
                blank=True, null=True, upload_to=purchase.models.upload_to_receipts
            ),
        ),
    ]
