# Generated by Django 5.1.3 on 2025-02-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="total_price",
        ),
    ]
