# Generated by Django 5.1.3 on 2025-02-18 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase",
            "0002_rename_transferred_from_item_transferred_from_bank_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="bank_name",
        ),
        migrations.AlterField(
            model_name="item",
            name="custom_item_name",
            field=models.CharField(
                blank=True, default=datetime.date.today, max_length=100
            ),
            preserve_default=False,
        ),
    ]
