# Generated by Django 5.1.3 on 2025-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0002_remove_item_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("with", "With"), ("without", "Without")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                choices=[
                    ("Shanks", "Shanks"),
                    ("Rods", "Rods"),
                    ("Bits", "Bits"),
                    ("Couplings", "Couplings"),
                    ("Liquid consumables", "Liquid consumables"),
                    ("Gas consumables", "Gas consumables"),
                    ("Filters", "Filters"),
                    ("Maintenance Items", "Maintenance Items"),
                ],
                max_length=100,
            ),
        ),
    ]
