# Generated by Django 5.1.3 on 2025-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0003_item_total_price_alter_item_category_alter_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_class",
            field=models.CharField(
                choices=[
                    ("Main Consumables", "Main Consumables"),
                    ("Lubricants", "Lubricants"),
                    ("Service Items", "Service Items"),
                    ("Maintenance Items", "Maintenance Items"),
                ],
                default="A",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
