# Generated by Django 5.1.3 on 2025-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0003_alter_item_bank_transfer_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="receipt_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/receipts/"
            ),
        ),
    ]
