# Generated by Django 5.1.3 on 2025-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_alter_item_receipt_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="USD_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="payment_transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("Bank Transfer", "Bank Transfer"), ("Cash", "Cash")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="date_of_bank_transfer",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="payment_type",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Paid", "Paid in Full")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
