# Generated by Django 5.1.3 on 2025-02-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_item_item_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Main Consumables", "Main Consumables"),
                    ("Lubricants", "Lubricants"),
                    ("Service Items", "Service Items"),
                    ("Maintenance Items", "Maintenance Items"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
