# Generated by Django 5.1.3 on 2025-02-28 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_alter_item_receipt_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="payment_transaction_type",
            field=models.CharField(
                choices=[("Bank Transfer", "Bank Transfer"), ("Cash", "Cash")],
                default=django.utils.timezone.now,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="payment_type",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Paid", "Paid in Full")], max_length=100
            ),
        ),
    ]
