# Generated by Django 5.1.3 on 2025-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_alter_item_item_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                choices=[
                    ("Shanks", "Shanks"),
                    ("Rods", "Rods"),
                    ("Bits", "Bits"),
                    ("Couplings", "Couplings"),
                    ("Liquid consumables", "Liquid consumables"),
                    ("Gas consumables", "Gas consumables"),
                    ("Filters", "Filters"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
