# Generated by Django 5.1.3 on 2025-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_item_usd_rate_item_payment_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
