# Generated by Django 5.1.3 on 2025-03-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_item_payment_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="payment_transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("Bank Transfer", "Bank Transfer"), ("Cash", "Cash")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
