# Generated by Django 5.1.3 on 2025-02-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0006_alter_item_color_alter_item_model_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                choices=[
                    ("Shank", "Shank"),
                    ("Rod", "Rod"),
                    ("Bits", "Bit"),
                    ("Coupling", "Coupling"),
                    ("Liquid consumable", "Liquid consumable"),
                    ("Gas consumable", "Gas consumable"),
                    ("Filter", "Filter"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
