# Generated by Django 5.1.3 on 2025-03-02 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0006_alter_item_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_destination",
            field=models.CharField(
                choices=[("To Warehouse", "To Warehouse"), ("To Site", "To Site")],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
