# Generated by Django 5.1.3 on 2025-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_alter_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="custom_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                choices=[
                    ("Shank", "Shank"),
                    ("Rod", "Rod"),
                    ("Bit", "Bit"),
                    ("Coupling", "Coupling"),
                    ("Liquid consumable", "Liquid consumable"),
                    ("Gas consumable", "Gas consumable"),
                    ("Filter", "Filter"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
