# Generated by Django 5.1.3 on 2025-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_item_item_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="USD_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="date_of_bank_transfer",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_destination",
            field=models.CharField(
                choices=[
                    ("Item Taken", "Item Taken"),
                    ("Item Not Taken", "Item Not Taken"),
                ],
                max_length=50,
            ),
        ),
    ]
