# Generated by Django 5.1.3 on 2025-03-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase",
            "0008_alter_item_usd_rate_alter_item_date_of_bank_transfer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="total_price_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
