# Generated by Django 5.1.3 on 2025-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0009_item_total_price_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="receipt_status",
            field=models.CharField(
                blank=True,
                choices=[("Taken", "Taken"), ("Not Taken", "Not Taken")],
                max_length=50,
                null=True,
            ),
        ),
    ]
