# Generated by Django 5.1.3 on 2025-03-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0010_item_receipt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
