# Generated by Django 5.1.3 on 2025-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0011_alter_item_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="FS_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Main Consumables", "Main Consumables"),
                    ("Lubricants", "Lubricants"),
                    ("Service Items", "Service Items"),
                    ("Maintenance Items", "Maintenance Items"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_destination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Item Taken", "Item Taken"),
                    ("Item Not Taken", "Item Not Taken"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
