# Generated by Django 5.1.3 on 2025-03-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0012_alter_item_fs_number_alter_item_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="withholding",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
