# Generated by Django 5.1.3 on 2025-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0013_item_withholding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="FS_number",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
