# Generated by Django 5.1.3 on 2025-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0014_alter_item_fs_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="FS_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="payment_transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("Cash", "Cash"),
                    ("Deposit to Bank", "Deposit to Bank"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
