# Generated by Django 5.1.3 on 2025-02-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items_used", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsused",
            name="quantity_used",
            field=models.PositiveIntegerField(),
        ),
    ]
