# Generated by Django 5.1.3 on 2025-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items_used", "0002_alter_itemsused_quantity_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsused",
            name="person_responsible",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
